---
- name: Hello World!
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Cisco Facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: my_facts
      
    - name: Write Output
      debug:
         msg: "{{my_facts}}"
         
    - name: run show version on remote devices
      cisco.ios.ios_command:  
        commands: show version 
      #become: yes
      #become_method: enable
