---
- name: Hello World!
  hosts: all
  gather_facts: yes
 
  tasks:
    - name: Write Output
      debug:
         msg: "{{hostvars}}"
    - name: run show version on remote devices
      cisco.ios.ios_command:  
        commands: show version 
      #become: yes
      #become_method: enable
