---
- name: Hello World!
  hosts: all
  gather_facts: no 
 
  tasks:
    - name: Hello World!
      shell: echo "Hi! Tower is working."
    - name: Write Output
      debug:
         msg: "Something here"
    - name: Ping
      action: ping
