---
- name: Hello World!
  hosts: all
  gather_facts: no
  ansible_connection: ansible.netcommon.network_cli 
 
  tasks:
    - name: Write Output
      debug:
         msg: "Something here"
    - name: run show version on remote devices
      cisco.ios.ios_command:
        commands: show version
