---
- name: Hello World!
  hosts: all
  gather_facts: no 
 
  tasks:
    - name: Write Output
      debug:
         msg: "Something here"
    - name: run show version on remote devices
      cisco.ios.ios_command:  
        commands: show version 
      become: yes
      become_method: enable
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
